const CartActionTypes={
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEM:'ADD_CART_ITEM',
    REMOVE_ITEM_FROM_CART:'REMOVE_ITEM_FROM_CART',
    REMOVE_QUANTITY:'REMOVE_QUANTITY'
};

export default CartActionTypes;